# Generated by Django 4.2.13 on 2025-08-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('posted_at', models.DateTimeField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
